language: node_js
node_js:
  - 12.12.0
addons:
  ssh_known_hosts:
    - 140.82.39.61
before_install:
  - openssl aes-256-cbc -K $encrypted_d9994d39f69d_key -iv $encrypted_d9994d39f69d_iv
    -in .travis/deploy_rsa.enc -out .travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
  edge: true
  on:
    branch: master
